apiVersion: v1
kind: Service
metadata:
    name: "test05068723-f45f"
    labels:
        app: "test05068723-f45f"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "test05068723-f45f"